version: '3'

services:
  app:
    build:
      context: app
    ports:
      - "5000"

  nginx:
    container_name: nginx
    build: nginx
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"